#pragma once
#include "AnimatorComponent.h"
#include "BaseComponent.h"
#include "InputComponent.h"
#include "RenderComponent.h"
#include "stateMachineComponent.h"
#include "TextComponent.h"
#include "TransformComponent.h"
#include "GridComponent.h"